GET http://localhost:3000/genres HTTP/1.1
###
GET http://localhost:3000/genres/5c59cf815450ab0a88be6d60 HTTP/1.1
###

POST http://localhost:3000/genres/ HTTP/1.1
content-type: application/json

{
    "name": "Fantasy"
}
###
PUT http://localhost:3000/genres/5c59c107d19fb123a402d30b HTTP/1.1
content-type: application/json

{
    "name": "Drama"
}

###
DELETE  http://localhost:3000/genres/5c5c05acf48cc11540eba996 HTTP/1.1

###
GET http://localhost:3000/costumers HTTP/1.1

###
GET http://localhost:3000/costumers/5c5c1ed75c28671208014359 HTTP/1.1

###
POST http://localhost:3000/costumers/ HTTP/1.1
content-type: application/json

{
    "isGold": false,
    "name": "Gillardo Josefo",
    "phone": "985274893"
}

###
PUT http://localhost:3000/costumers/5c5c1ed75c28671208014359 HTTP/1.1
content-type: application/json

{
    "name": "Percian Prince"
}

###
DELETE  http://localhost:3000/costumers/5c5c20d2d3eb7603a8b2a56d  HTTP/1.1

###

GET  http://localhost:3000/movies/ HTTP/1.1

###

POST http://localhost:3000/movies/ HTTP/1.1
content-type: application/json

{
    "title": "Narnia Chronics",
    "genreId": "5c6b0a7f82faa823b07919d4",
    "numberInStock": "12",
    "dailyRentalRate": "3.1"
}

###

PUT http://localhost:3000/movies/5c6492640613ae748f56d735 HTTP/1.1
content-type: application/json

{
    "title": "External Mind",
    "genreId": "5c59c107d19fb123a402d30b",
    "numberInStock": "10",
    "dailyRentalRate": "2.4"
}

###

DELETE  http://localhost:3000/movies/5c66e430551d615284467273 HTTP/1.1

###

POST http://localhost:3000/api/rentals/ HTTP/1.1
content-type: application/json

{
    "customerId": "5c6b116433a83f1fd842f12b",
    "movieId": "5c6b0b4e82faa823b07919d5"
}

###

GET http://localhost:3000/api/rentals/ HTTP/1.1