GET http://localhost:3000/genres HTTP/1.1
###
GET http://localhost:3000/genres/5c59c12bd19fb123a402d30d HTTP/1.1
###

POST http://localhost:3000/genres/ HTTP/1.1
content-type: application/json

{
    "name": "Pseudu"
}
###
PUT http://localhost:3000/genres/5c59d65d5450ab0a88be6d66 HTTP/1.1
content-type: application/json

{
    "name": "Pseudo"
}

###
DELETE  http://localhost:3000/genres/5c59c12bd19fb123a402d30d HTTP/1.1