GET http://localhost:3000/genres HTTP/1.1
###
GET http://localhost:3000/genres/5c59cf815450ab0a88be6d60 HTTP/1.1
###

POST http://localhost:3000/genres/ HTTP/1.1
content-type: application/json

{
    "name": ""
}
###
PUT http://localhost:3000/genres/5c59c107d19fb123a402d30b HTTP/1.1
content-type: application/json

{
    "name": "Drama"
}

###
DELETE  http://localhost:3000/genres/5c5c05acf48cc11540eba996 HTTP/1.1

###
GET http://localhost:3000/costumers HTTP/1.1

###
GET http://localhost:3000/costumers/5c5c1ed75c28671208014359 HTTP/1.1

###
POST http://localhost:3000/costumers/ HTTP/1.1
content-type: application/json

{
    "isGold": false,
    "name": "Tranbolping Baby",
    "phone": "99383829"
}

###
PUT http://localhost:3000/costumers/5c5c1ed75c28671208014359 HTTP/1.1
content-type: application/json

{
    "name": "Percian Prince"
}

###
DELETE  http://localhost:3000/costumers/5c5c20d2d3eb7603a8b2a56d  HTTP/1.1

###

GET  http://localhost:3000/movies/ HTTP/1.1

###

POST http://localhost:3000/movies/ HTTP/1.1
content-type: application/json

{
    "title": "Matrix",
    "genreId": "5c680286270ac96ae14ad961",
    "numberInStock": "10",
    "dailyRentalRate": "2.1"
}

###

PUT http://localhost:3000/movies/5c6492640613ae748f56d735 HTTP/1.1
content-type: application/json

{
    "title": "External Mind",
    "genreId": "5c59c107d19fb123a402d30b",
    "numberInStock": "10",
    "dailyRentalRate": "2.4"
}

###

DELETE  http://localhost:3000/movies/5c66e430551d615284467273 HTTP/1.1

###

POST http://localhost:3000/rentals/ HTTP/1.1
content-type: application/json

{
    "initDate":"2019-02-16",
    "customerId": "5c5c1e8e5c28671208014358",
    "movieId": "5c64918b097683736cba97b1",
    "amountOfDays": "2"
}